FROM python:3.12-slim

WORKDIR /dashboard

COPY requirements.txt .
RUN pip3 install -r requirements.txt

EXPOSE 8501 

RUN mkdir ./pages
COPY ./pages ./pages

RUN mkdir ./streamlit
COPY ./.streamlit ./.streamlit

COPY main_page.py .

CMD streamlit run main_page.py --server.port 8501


