FROM python:latest


WORKDIR /dashboard

COPY requirements.txt .
RUN pip3 install -r requirements.txt

EXPOSE 8501 

RUN  mkdir ./pages
COPY ./pages ./pages

RUN mkdir ./streamlit
COPY ./.streamlit ./.streamlit

COPY main_page.py .


# Instructions for running streamlit dashboard
CMD streamlit run main_page.py --server.port 8501




# RUN LOCALLY
    # docker build -t raiway-tracker-dashboard-local .
    # docker image ls
    # docker run -it -p 8501:8501 --env-file .env raiway-tracker-dashboard-local 

# AWS ECR PUSH COMMANDS:
    # aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 129033205317.dkr.ecr.eu-west-2.amazonaws.com
    # docker build --platform "linux/amd64" -t c11-raiway-tracker-dashboard . 
    # docker tag c11-raiway-tracker-dashboard:latest 129033205317.dkr.ecr.eu-west-2.amazonaws.com/c11-raiway-tracker-dashboard:latest
    # docker push 129033205317.dkr.ecr.eu-west-2.amazonaws.com/c11-raiway-tracker-dashboard:latest

# external link: 

